language: node_js
node_js:
  - "0.10"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - "travis_retry npm install grunt-cli"
  - "travis_retry npm install"
